import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { takeUntilDestroyed, toSignal } from '@angular/core/rxjs-interop';
import { AbstractControl, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MembershipFeeService } from '../services/membership-fee.service';
import { DialogComponent } from '../shared/dialog/dialog';
import { MoneyInputDirective } from '../shared/money-input.directive';
import { MembershipFee, MembershipStatusOption, TaxSchemeRef } from '../models/auth.models';

interface StageRow {
  stageNo: number;
  amount: string; // kept as string for the input; parsed on save
  isPosted: boolean;
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

// Membership Management → Master File Setup → Membership Fee.
// Per-company master file: fee header + an installment schedule (Membership Fee
// Scheme) generated by splitting the amount into N stages, then editable.
//
// Reactive Forms (canonical reference: platform-users). One typed nonNullable
// FormGroup drives the create+edit dialog: validators live on the controls (not
// hand-rolled in onSave), `form.dirty` feeds the shared dialog's unsaved-changes
// guard, and every field carries its correct HTML5 input type. The optional
// installment fields (noOfInstallment / installmentInterval) become required and
// enabled only while "Allow installment" is on — wired through the checkbox
// control's valueChanges.
@Component({
  selector: 'app-membership-fees',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, DialogComponent, MoneyInputDirective],
  templateUrl: './membership-fees.html',
  styleUrls: ['../system-setup/system-setup.css', './membership-fees.css'],
})
export class MembershipFeesComponent implements OnInit {
  private readonly service = inject(MembershipFeeService);
  private readonly fb = inject(FormBuilder);

  readonly fees = signal<MembershipFee[]>([]);
  readonly intervals = signal<MembershipStatusOption[]>([]);
  readonly taxSchemes = signal<TaxSchemeRef[]>([]);
  readonly countrySet = signal(true);
  readonly loading = signal(false);
  readonly togglingId = signal<string | null>(null);

  // Add/edit dialog. `editId` null = create mode.
  readonly dialogOpen = signal(false);
  readonly saving = signal(false);
  editId = signal<string | null>(null);

  // Single typed form for both create and edit. nonNullable keeps the always-on
  // controls non-null; noOfInstallment stays nullable so an empty schedule reads
  // back as null. The installment controls start disabled (revealed by the toggle).
  readonly form = this.fb.nonNullable.group({
    membershipFeeCode: ['', [Validators.required, Validators.maxLength(50)]],
    description: ['', [Validators.maxLength(200)]],
    taxSchemeCode: [''],
    amount: [0, [Validators.required, Validators.min(0)]],
    allowInstallment: [false],
    noOfInstallment: this.fb.control<number | null>({ value: null, disabled: true }),
    installmentInterval: this.fb.control<string>({ value: '', disabled: true }),
  });

  // Installment stages (Membership Fee Scheme detail) — not a form control; the
  // rows are generated then edited in place.
  readonly stages = signal<StageRow[]>([]);

  // Mirror the live form value into a signal so the amount/balance computeds and
  // the dialog title stay reactive to typing.
  private readonly formValue = toSignal(this.form.valueChanges, {
    initialValue: this.form.getRawValue(),
  });

  readonly search = signal('');
  readonly successMessage = signal('');
  readonly errorMessage = signal('');

  readonly filtered = computed(() => {
    const q = this.search().trim().toLowerCase();
    const sorted = [...this.fees()].sort((a, b) => {
      const aActive = a.isActive !== false;
      const bActive = b.isActive !== false;
      if (aActive !== bActive) return aActive ? -1 : 1;
      return a.membershipFeeCode.localeCompare(b.membershipFeeCode);
    });
    if (!q) return sorted;
    return sorted.filter(
      (f) =>
        f.membershipFeeCode.toLowerCase().includes(q) ||
        (f.description || '').toLowerCase().includes(q) ||
        (f.taxSchemeCode || '').toLowerCase().includes(q),
    );
  });
  readonly activeCount = computed(() => this.fees().filter((f) => f.isActive !== false).length);

  readonly dialogTitle = computed(() =>
    this.editId() ? `Edit — ${this.formValue().membershipFeeCode ?? ''}` : 'New membership fee',
  );

  // Live total of the installment stages, for the sum-must-match hint.
  readonly stageTotal = computed(() => round2(this.stages().reduce((sum, s) => sum + (Number(s.amount) || 0), 0)));
  readonly amountValue = computed(() => round2(Number(this.formValue().amount) || 0));
  readonly scheduleBalanced = computed(() => this.stageTotal() === this.amountValue());

  constructor() {
    // Allow-installment toggle: reveal + require the schedule fields when on,
    // clear/disable them when off. Runs on programmatic reset too, so opening the
    // dialog puts the two controls into the right state automatically.
    this.form.controls.allowInstallment.valueChanges
      .pipe(takeUntilDestroyed())
      .subscribe((allow) => this.syncInstallmentControls(allow));
  }

  ngOnInit(): void {
    this.loadMeta();
    this.loadTaxSchemes();
    this.load();
  }

  // Apply/clear the conditional validators and enabled state for the two
  // installment controls based on the checkbox.
  private syncInstallmentControls(allow: boolean): void {
    const no = this.form.controls.noOfInstallment;
    const interval = this.form.controls.installmentInterval;
    if (allow) {
      no.setValidators([Validators.required, Validators.min(1)]);
      interval.setValidators([Validators.required]);
      no.enable({ emitEvent: false });
      interval.enable({ emitEvent: false });
    } else {
      no.clearValidators();
      interval.clearValidators();
      no.reset(null, { emitEvent: false });
      interval.reset('', { emitEvent: false });
      no.disable({ emitEvent: false });
      interval.disable({ emitEvent: false });
      this.stages.set([]);
    }
    no.updateValueAndValidity({ emitEvent: false });
    interval.updateValueAndValidity({ emitEvent: false });
  }

  // Show a control's validation message once the user has interacted with it
  // (or after a submit attempt marks everything touched).
  showError(control: AbstractControl): boolean {
    return control.invalid && control.touched;
  }

  intervalLabel(key: string | null | undefined): string {
    if (!key) return '';
    return this.intervals().find((i) => i.key === key)?.label || key;
  }

  loadMeta(): void {
    this.service.meta().subscribe({
      next: (m) => this.intervals.set(m.intervals),
      error: () => {},
    });
  }

  loadTaxSchemes(): void {
    this.service.taxSchemes().subscribe({
      next: (r) => {
        this.taxSchemes.set(r.schemes);
        this.countrySet.set(r.countrySet);
      },
      error: () => {},
    });
  }

  load(): void {
    this.loading.set(true);
    this.service.list().subscribe({
      next: (data) => {
        this.fees.set(data);
        this.loading.set(false);
      },
      error: (err) => {
        this.loading.set(false);
        this.errorMessage.set(err.error?.message || 'Failed to load membership fees.');
      },
    });
  }

  openAdd(): void {
    this.clearMessages();
    this.editId.set(null);
    // reset seeds a pristine form (keeps the dialog's dirty-guard + Save state
    // correct); the allowInstallment=false emission disables the schedule fields.
    this.form.reset({
      membershipFeeCode: '',
      description: '',
      taxSchemeCode: '',
      amount: 0,
      allowInstallment: false,
      noOfInstallment: null,
      installmentInterval: '',
    });
    this.stages.set([]);
    this.dialogOpen.set(true);
  }

  openEdit(fee: MembershipFee): void {
    this.clearMessages();
    this.editId.set(fee.id);
    this.form.reset({
      membershipFeeCode: fee.membershipFeeCode,
      description: fee.description || '',
      taxSchemeCode: fee.taxSchemeCode || '',
      amount: Number(fee.amount ?? 0),
      allowInstallment: !!fee.allowInstallment,
      noOfInstallment: fee.noOfInstallment ?? null,
      installmentInterval: fee.installmentInterval || '',
    });
    // Set the stages AFTER reset: a reset with allowInstallment=false clears them.
    this.stages.set((fee.stages || []).map((s) => ({ stageNo: s.stageNo, amount: String(s.amount), isPosted: !!s.isPosted })));
    this.dialogOpen.set(true);
  }

  closeDialog(): void {
    this.dialogOpen.set(false);
  }

  // Split the amount equally into N stages; the remainder lands on the last stage.
  generateSchedule(): void {
    this.clearMessages();
    const n = Number(this.form.controls.noOfInstallment.value);
    const amount = this.amountValue();
    if (!Number.isInteger(n) || n < 1) {
      this.errorMessage.set('Enter a whole number of installments first.');
      return;
    }
    if (amount <= 0) {
      this.errorMessage.set('Enter the fee amount before generating the schedule.');
      return;
    }
    const base = Math.floor((amount / n) * 100) / 100;
    const rows: StageRow[] = [];
    for (let i = 1; i <= n; i++) {
      const amt = i === n ? round2(amount - base * (n - 1)) : base;
      rows.push({ stageNo: i, amount: amt.toFixed(2), isPosted: false });
    }
    this.stages.set(rows);
  }

  updateStageAmount(index: number, value: string): void {
    this.stages.update((rows) => rows.map((r, i) => (i === index ? { ...r, amount: value } : r)));
  }

  onSave(): void {
    this.clearMessages();
    if (this.form.invalid) {
      this.form.markAllAsTouched(); // reveal every field's error at once
      return;
    }
    const v = this.form.getRawValue();
    const amount = round2(Number(v.amount) || 0);

    const payload: Partial<MembershipFee> = {
      membershipFeeCode: v.membershipFeeCode.trim(),
      description: v.description.trim() || null,
      taxSchemeCode: v.taxSchemeCode || null,
      amount,
      allowInstallment: v.allowInstallment,
      noOfInstallment: null,
      installmentInterval: null,
      stages: [],
    };

    if (v.allowInstallment) {
      const n = Number(v.noOfInstallment);
      if (!Number.isInteger(n) || n < 1) {
        this.errorMessage.set('Number of installments must be a whole number of at least 1.');
        return;
      }
      if (!v.installmentInterval) {
        this.errorMessage.set('Select an installment interval.');
        return;
      }
      if (this.stages().length !== n) {
        this.errorMessage.set(`Generate the schedule so it has ${n} stage(s).`);
        return;
      }
      if (!this.scheduleBalanced()) {
        this.errorMessage.set(`Stage amounts must total the fee amount (${amount.toFixed(2)}).`);
        return;
      }
      payload.noOfInstallment = n;
      payload.installmentInterval = v.installmentInterval;
      payload.stages = this.stages().map((s) => ({ stageNo: s.stageNo, amount: round2(Number(s.amount) || 0) }));
    }

    this.saving.set(true);
    const id = this.editId();
    const req$ = id ? this.service.update(id, payload) : this.service.create(payload);
    req$.subscribe({
      next: () => {
        this.successMessage.set(`${payload.membershipFeeCode} ${id ? 'updated' : 'added'}.`);
        this.saving.set(false);
        this.dialogOpen.set(false);
        this.load();
      },
      error: (err) => {
        this.errorMessage.set(err.error?.message || 'Failed to save membership fee.');
        this.saving.set(false);
      },
    });
  }

  toggleActive(fee: MembershipFee): void {
    this.clearMessages();
    const next = !(fee.isActive !== false);
    this.togglingId.set(fee.id);
    this.service.setActive(fee.id, next).subscribe({
      next: () => {
        this.successMessage.set(`${fee.membershipFeeCode} ${next ? 'enabled' : 'disabled'}.`);
        this.togglingId.set(null);
        this.load();
      },
      error: (err) => {
        this.errorMessage.set(err.error?.message || 'Failed to update membership fee.');
        this.togglingId.set(null);
      },
    });
  }

  clearSearch(): void {
    this.search.set('');
  }

  private clearMessages(): void {
    this.successMessage.set('');
    this.errorMessage.set('');
  }
}
