import { Injectable, computed, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { NavigationEnd, Router } from '@angular/router';
import { takeUntilDestroyed, toSignal } from '@angular/core/rxjs-interop';
import { filter, map } from 'rxjs';

// In-app help: screens get a self-explaining user manual, keyed by ROUTE.
//
// Manuals are generated by the /user-manual skill as static assets under
// /help/<route-slug>.md plus a manifest at /help/index.json listing which slugs
// exist (with a display title). The manifest is the existence check - nginx's
// SPA fallback answers 200 + index.html for ANY unknown path, so probing the
// .md directly could never distinguish "no manual" from "manual".
//
// Route -> slug: the url without query/fragment, segments joined by '-'
// (/admin/countries -> admin-countries). For parameterised routes the lookup
// drops trailing segments until it hits a manifest entry, so a detail view
// like /admin/tax-schemes/<id> resolves to the tax-schemes manual.
// The Book icon in the header appears automatically for any route that
// resolves - publishing a manual is all it takes to light it up.

export interface HelpManifestEntry {
  title: string;
}

@Injectable({ providedIn: 'root' })
export class HelpService {
  private readonly http = inject(HttpClient);
  private readonly router = inject(Router);

  private readonly manifest = signal<Record<string, HelpManifestEntry> | null>(null);

  private readonly currentUrl = toSignal(
    this.router.events.pipe(
      filter((e): e is NavigationEnd => e instanceof NavigationEnd),
      map((e) => e.urlAfterRedirects),
    ),
    { initialValue: this.router.url },
  );

  /** The manifest slug for the current route, or null when no manual exists. */
  readonly currentSlug = computed<string | null>(() => {
    const manifest = this.manifest();
    if (!manifest) return null;
    const url = this.currentUrl().split('?')[0].split('#')[0];
    const segments = url.split('/').filter(Boolean);
    // Longest match first, then drop trailing segments (detail routes fall
    // back to their list screen's manual).
    for (let end = segments.length; end > 0; end--) {
      const slug = segments.slice(0, end).join('-');
      if (manifest[slug]) return slug;
    }
    return null;
  });

  /** Title of the current route's manual (for the panel header). */
  readonly currentTitle = computed<string>(() => {
    const slug = this.currentSlug();
    return (slug && this.manifest()?.[slug]?.title) || 'Help';
  });

  constructor() {
    // One small fetch per session; a missing/broken manifest simply means no
    // Book icons anywhere (never an error the user sees).
    this.http
      .get<Record<string, HelpManifestEntry>>('/help/index.json')
      .pipe(takeUntilDestroyed())
      .subscribe({
        next: (m) => this.manifest.set(m ?? {}),
        error: () => this.manifest.set({}),
      });
  }

  /** Fetch the current manual's Markdown source. */
  loadManual(slug: string) {
    return this.http.get(`/help/${slug}.md`, { responseType: 'text' });
  }
}
