const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

/**
 * OutboxMessages Model
 * Used for the Transactional Outbox Pattern to ensure Atomicity 
 * between Database updates and Message Broker events.
 */
const OutboxMessage = sequelize.define('OutboxMessage', {
    // 1. Identity: UUID generated by the application
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
    },

    // 2. Routing: The event type (e.g., 'OrderCreated')
    type: {
        type: DataTypes.STRING(200),
        allowNull: false,
    },

    // 3. The Data: Flexible JSONB for high-speed indexing
    payload: {
        type: DataTypes.JSONB,
        allowNull: false,
    },

    // 👇 ADD THESE TWO COLUMNS 👇
    status: {
        type: DataTypes.STRING,
        defaultValue: 'PENDING', // Can be PENDING, COMPLETED, or FAILED
    },
    
    retryCount: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
    },

    // 4. Timestamp: When the transaction occurred
    occurredOn: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW, // Maps to (NOW() AT TIME ZONE 'utc')
    },

    // 5. Status: Timestamp of when the worker finished processing
    processedDate: {
        type: DataTypes.DATE,
        allowNull: true,
    },

    // 6. Debugging: Error details if the background worker fails
    errorLog: {
        type: DataTypes.TEXT,
        allowNull: true,
    }
}, {
    tableName: 'OutboxMessage',
    // We disable standard timestamps (createdAt/updatedAt) because we 
    // use occurredOn and processedDate for specialized tracking.
    timestamps: false, 
    
    // --- CRITICAL INDEX CONFIGURATION ---
    indexes: [
        {
            name: 'IDX_OutboxMessage_Pending',
            fields: ['occurredOn'],
            // Partial/Filtered Index: Only indexes messages that haven't been sent.
            // This makes the worker polling query extremely efficient.
            where: {
                processedDate: null
            }
        }
    ]
});

module.exports = OutboxMessage;